# Generated by Django 3.2.19 on 2023-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('NEW', 'News'), ('ART', 'Article')], default='NEW', max_length=3)),
                ('text', models.TextField()),
                ('date_on', models.DateField()),
            ],
        ),
    ]
