# Generated by Django 3.2.19 on 2023-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
