# Generated by Django 3.2.19 on 2023-08-29 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscriber',
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ARTICLE', 'ARTICLE')], default='ARTICLE', max_length=8),
        ),
    ]
