# Generated by Django 3.2.19 on 2023-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_alter_news_date_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Article', 'Article')], default='News', max_length=7),
        ),
    ]
